config/routes.rb
Minidoudou::Application.routes.draw do

  match "userlist", :to => "userlist#index"
  match "userlist/:id/delete", :to => "userlist#delete", :via => "delete", :as => "user_delete"
  match "userlist/:id/toggleadmin", :to => "userlist#toggleadmin", :as => "admin_toggle"

  devise_for :users

  resources :apks

  resources :packages
  
  resources :devices do
    resources :base_roms do
      resources :base_rom_packages
      resources :configurations
      get 'purge_configs'
      get 'purge_test_configs'
    end
  end

  root :to => "devices#index"

end

app/controllers/userlist_controller.rb
class UserlistController < ApplicationController
  def index
    authorize! :manage, :user
    @users = User.all.sort_by {|u| u.admin ? 0 : 1 }
  end

  def delete
    authorize! :manage, :user
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to userlist_path, :notice => "Suicidal much?"
    else
      @user.destroy
      redirect_to userlist_path, :notice => "User '#{@user.name}' deleted"
    end
  end

  def toggleadmin
    authorize! :manage, :user
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to userlist_path, :notice => "Nope, bad idea"
    else
      @user.update_attribute :admin, !@user.admin
      redirect_to userlist_path, :notice => "User '#{@user.name}' updated"
    end
  end
end

app/helpers/userlist_helper.rb
module UserlistHelper
end

app/views/userlist/_user.html.erb
<li>
  <% if user.admin %><strong><% end %>
  <%= user.name %>
  <% if user.admin %></strong><% end %>
  (<%= user.base_roms.collect {|br| "#{br.name} for #{br.device.name}"}.join(",")%>)
  <%= link_to 'Delete', user_delete_path(user), :method => :delete, :confirm => 'Are you sure?' %>
  <%= link_to (user.admin ? "Kick" : "Make")+" admin", admin_toggle_path(user), :confirm => 'Are you sure?' %>
</li>

app/views/userlist/index.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  Users
<% end %>

<ul>
  <%= render :partial => "user", :collection => @users %>
</ul>