config/routes.rb
Minidoudou::Application.routes.draw do

  match "userlist", :to => "userlist#index"
  match "userlist/:id/delete", :to => "userlist#delete", :via => "delete", :as => "user_delete"
  match "userlist/:id/toggleadmin", :to => "userlist#toggleadmin", :as => "admin_toggle"

  devise_for :users

  resources :apks

  resources :packages
  
  resources :devices do
    resources :base_roms do
      resources :base_rom_packages
      resources :configurations
      get 'purge_configs'
      get 'purge_test_configs'
    end
  end

  root :to => "devices#index"

end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :base_roms

  validates_presence_of :name
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  load_and_authorize_resource

  # GET /devices
  # GET /devices.xml
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /devices/1
  # GET /devices/1.xml
  def show
    @current_base_roms = @device.base_roms.select{|br| !br.old && !br.dev}
    @deprecated_base_roms = @device.base_roms.select{|br| br.old && !br.dev}
    @dev_base_roms = @device.base_roms.select{|br| br.dev && current_user.owns_rom(br)}
    
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /devices/new
  # GET /devices/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.xml
  def create
    respond_to do |format|
      if @device.save
        format.html { redirect_to(@device, :notice => 'Device was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.xml
  def update
    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to(@device, :notice => 'Device was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.xml
  def destroy
    @device.destroy

    respond_to do |format|
      format.html { redirect_to(devices_url) }
    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_base_rom.html.erb
<% if base_roms.any? %>
  <h3><a href="#"><%= section %> (<%= base_roms.count %>)</a></h3>
  <div>
    <ul>
    <% base_roms.each do |base_rom| %>
      <li><%= link_to base_rom.name, device_base_rom_configurations_path(@device, base_rom) %>
      <span class="uploader_name">(by <%= uploader_name_for base_rom %>)</span></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :system_size, '/system partition size (MB)' %><br />
    <%= f.text_field :system_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %> <%= image_tag 'nav_sep.png' %>
  <%= link_to @device.name, @device %> <%= image_tag 'nav_sep.png' %>
  Edit
<% end %>

<%= render 'form' %>

app/views/devices/index.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %> <%= image_tag 'nav_sep.png' %>
  Welcome to Minidoudou !
<% end %>

<h2>Select your device to get started</h2>

<ul>
<% @devices.each do |device| %>
  <li><%= device.image_url %> <%= link_to device.name, device %></li>
<% end %>
</ul>

<p>Minidoudou is still under development, so don't expect too much right now... After a first test phase, I will be looking for contributors to support more devices and ROMs.</p>
<p>Join me on <a href="http://forum.xda-developers.com/showthread.php?t=834868">XDA developers</a> to give your opinion and discuss features!</p>
<p>You can check out the source code and report bugs on <a href="https://github.com/joelcogen/minidoudou">GitHub</a>.</p>

<% content_for :admin do %>
  <% if can? :create, :device %>
    <%= link_to 'New device', new_device_path %> |
  <% end %>
  <%= link_to 'Packages', packages_path %> |
  <%= link_to 'APKs', apks_path %> |
  <% if can? :manage, :user %>
    <%= link_to 'Users', userlist_path %> |
  <% end %>
  <%= link_to 'Log', 'log' %>
<% end %>

app/views/devices/new.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %> <%= image_tag 'nav_sep.png' %>
  New device
<% end %>

<%= render 'form' %>

app/views/devices/show.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %> <%= image_tag 'nav_sep.png' %>
  <%= @device.name %>
<% end %>

<script language="javascript">
  $(function() {
	  $('#accordion').accordion();
  });
</script>

<h2>Select a ROM to customize</h2>

<div id="accordion">
  <%= render :partial => 'base_rom', :locals => {:section => 'Current', :base_roms => @current_base_roms} %>
  <%= render :partial => 'base_rom', :locals => {:section => 'In development (only visible by you)', :base_roms => @dev_base_roms} %>
  <%= render :partial => 'base_rom', :locals => {:section => 'Deprecated', :base_roms => @deprecated_base_roms} %>
</div>

<% content_for :admin do %>
  <% if can? :edit, @device %>
    <%= link_to 'Edit device', edit_device_path(@device) %> |
  <% end %>
  <%= link_to 'New ROM', new_device_base_rom_path(@device) %>
<% end %>