config/routes.rb
Minidoudou::Application.routes.draw do

  match "userlist", :to => "userlist#index"
  match "userlist/:id/delete", :to => "userlist#delete", :via => "delete", :as => "user_delete"
  match "userlist/:id/toggleadmin", :to => "userlist#toggleadmin", :as => "admin_toggle"

  devise_for :users

  resources :apks

  resources :packages
  
  resources :devices do
    resources :base_roms do
      resources :base_rom_packages
      resources :configurations
      get 'purge_configs'
      get 'purge_test_configs'
    end
  end

  root :to => "devices#index"

end

app/models/apk.rb
class Apk < ActiveRecord::Base
  belongs_to :base_rom

  validates_presence_of :name
end

app/controllers/apks_controller.rb
class ApksController < ApplicationController
  load_and_authorize_resource :except => :index

  # GET /apks
  # GET /apks.xml
  def index
    # CanCan doesn't load @apks here for some reason (it's got something to do with
    # the block in ability.rb, but I don't know what)
    @apks = Apk.find(:all, :conditions => {:base_rom_id => nil})
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /apks/1
  # GET /apks/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /apks/new
  # GET /apks/new.xml
  def new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /apks/1/edit
  def edit
  end

  # POST /apks
  # POST /apks.xml
  def create
    # Save file
    file_path = DataFile.store(params[:upload])
    unless file_path
      @apk.errors.add :file, 'upload failed, please try again'
      render :action => "new"
      return
    end
    @apk.location = file_path

    respond_to do |format|
      if @apk.save
        format.html { redirect_to(@apk, :notice => 'Apk was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /apks/1
  # PUT /apks/1.xml
  def update
    # Save file
    if params[:upload]
      file_path = DataFile.store(params[:upload])
      unless file_path
        @apk.errors.add :file, 'upload failed, please try again'
        render :action => "new"
        return
      end
      @apk.file_path = file_path
    end

    respond_to do |format|
      if @apk.update_attributes(params[:apk])
        format.html { redirect_to(@apk, :notice => 'Apk was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /apks/1
  # DELETE /apks/1.xml
  def destroy
    @apk.destroy

    respond_to do |format|
      format.html { redirect_to(apks_url) }
    end
  end
end

app/helpers/apks_helper.rb
module ApksHelper
end

app/views/apks/_form.html.erb
<%= form_for(@apk, :html => {:multipart => true}) do |f| %>
  <% if @apk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apk.errors.count, "error") %> prohibited this apk from being saved:</h2>

      <ul>
      <% @apk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.check_box :expert %> <%= f.label :expert %><br/>
    <%= f.check_box :deprecated %> <%= f.label :deprecated %>
  </div>

  <div class="field">
    <%= f.label 'Location:' %>
    <b><%= (@apk.location.nil? or @apk.location.empty? ) ? 'No file yet' : @apk.location %></b><br />
    <%= @apk.base_rom.nil? ? file_field('upload', 'datafile') : '' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apks/edit.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <% if @apk.base_rom.present? %>
    <%= link_to @apk.base_rom.device.name, @apk.base_rom.device %> <%= image_tag 'nav_sep.png' %>
    <%= link_to @apk.base_rom.name, [@apk.base_rom.device, @apk.base_rom] %> <%= image_tag 'nav_sep.png' %>
  <% else %>
    <%= link_to 'APKs', apks_path %> <%= image_tag 'nav_sep.png' %>
  <% end %>
  <%= link_to @apk.name, @apk %> <%= image_tag 'nav_sep.png' %>
  Edit
<% end %>

<%= render 'form' %>

app/views/apks/index.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  APKs
<% end %>

<ul>
<% @apks.sort_by {|a| a.deprecated ? 1 : 0}.each do |apk| %>
  <li>
    <strong><%= apk.deprecated ? "<s>".html_safe : "" %><%= link_to apk.name, apk %><%= apk.deprecated ? "</s>".html_safe : "" %></strong><br/>
    <%= apk.description %>
  </li>
<% end %>
</ul>

<% content_for :admin do %>
  <%= link_to 'New APK', new_apk_path %>
<% end %>

app/views/apks/new.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <%= link_to 'APKs', apks_path %> <%= image_tag 'nav_sep.png' %>
  New APK
<% end %>

<%= render 'form' %>

app/views/apks/show.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <% if @apk.base_rom.present? %>
    <%= link_to @apk.base_rom.device.name, @apk.base_rom.device %> <%= image_tag 'nav_sep.png' %>
    <%= link_to @apk.base_rom.name, [@apk.base_rom.device, @apk.base_rom] %> <%= image_tag 'nav_sep.png' %>
  <% else %>
    <%= link_to 'APKs', apks_path %> <%= image_tag 'nav_sep.png' %>
  <% end %>
  <%= link_to @apk.name, @apk %>
<% end %>

<p>
  <b>Base rom:</b>
  <%= @apk.base_rom.nil? ? "Extra" : link_to("#{@apk.base_rom.name} for #{@apk.base_rom.device.name}", [@apk.base_rom.device, @apk.base_rom]) %>
</p>

<p>
  <b>Name:</b>
  <%= @apk.name %>
</p>

<p>
  <b>Description:</b>
  <%= @apk.description %>
</p>

<p>
  <b>Location:</b>
  <%= @apk.location %>
</p>

<p>
  <b>Expert:</b>
  <%= yes_no @apk.expert %>
</p>

<p>
  <b>Deprecated:</b>
  <%= yes_no @apk.deprecated %>
</p>

<% content_for :admin do %>
  <%= link_to 'Edit', edit_apk_path(@apk) %> |
  <%= link_to 'Delete', @apk, :confirm => 'Really?', :method => :delete %>
<% end if can? :manage, @apk %>