config/routes.rb
Minidoudou::Application.routes.draw do

  match "userlist", :to => "userlist#index"
  match "userlist/:id/delete", :to => "userlist#delete", :via => "delete", :as => "user_delete"
  match "userlist/:id/toggleadmin", :to => "userlist#toggleadmin", :as => "admin_toggle"

  devise_for :users

  resources :apks

  resources :packages
  
  resources :devices do
    resources :base_roms do
      resources :base_rom_packages
      resources :configurations
      get 'purge_configs'
      get 'purge_test_configs'
    end
  end

  root :to => "devices#index"

end

app/models/base_rom.rb
class BaseRom < ActiveRecord::Base
  belongs_to :device
  belongs_to :uploader, :class_name => "User"
  has_many :apks, :dependent => :destroy
  has_many :base_rom_packages
  has_many :packages, :through => :base_rom_packages
  has_many :configurations

  validates :name, :presence => true

  def find_apks
    # Unzip
    Dir.mkdir "files/tmp_#{id}"
    system "unzip -qo #{file_path} -d files/tmp_#{id}/"

    # Find APKs
    Dir.entries("files/tmp_#{id}/system/app/").each do |apkname|
      next unless apkname.end_with? '.apk'
      apk = Apk.new(:base_rom_id => id,
                    :name        => apkname.gsub('.apk', ''),
                    :location    => 'system',
                    :expert      => true)
      apk.save
    end
    if File.exist? "files/tmp_#{id}/data/app/"
      Dir.entries("files/tmp_#{id}/data/app/").each do |apkname|
        next unless apkname.end_with? '.apk'
        apk = Apk.new(:base_rom_id => id,
                      :name        => apkname.gsub('.apk', ''),
                      :location    => 'data',
                      :expert      => true)
        apk.save
      end
    end

    # Cleanup
    system "rm -rf files/tmp_#{id}"
  end
end

app/controllers/base_roms_controller.rb
class BaseRomsController < ApplicationController
  before_filter :load_ressource, :except => [:new, :create]
  authorize_resource

  # GET /base_roms/1
  # GET /base_roms/1.xml
  def show
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /base_roms/new
  # GET /base_roms/new.xml
  def new
    @device = Device.find(params[:device_id])
    @base_rom = @device.base_roms.build
    @base_rom.dev = true

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /base_roms/1/edit
  def edit
    @device = Device.find(params[:device_id])
  end

  # POST /base_roms
  # POST /base_roms.xml
  def create
    @device = Device.find(params[:device_id])
    @base_rom = BaseRom.new(params[:base_rom])
    @base_rom.uploader = current_user

    # Save file
    file_path = DataFile.store(params[:upload])
    unless file_path
      @base_rom.errors.add :file, 'upload failed, please try again'
      render :action => "new"
      return
    end
    @base_rom.file_path = file_path

    respond_to do |format|
      if @base_rom.save
        @base_rom.find_apks
        format.html { redirect_to([@device, @base_rom], :notice => 'Base rom was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /base_roms/1
  # PUT /base_roms/1.xml
  def update
    @device = Device.find(params[:device_id])

    # Save file
    if params[:upload]
      file_path = DataFile.store(params[:upload])
      unless file_path
        @base_rom.errors.add :file, 'upload failed, please try again'
        render :action => "new"
        return
      end
      @base_rom.file_path = file_path
      # Refresh APKs
      @base_rom.apks.each &:delete
      @base_rom.find_apks
    end

    respond_to do |format|
      if @base_rom.update_attributes(params[:base_rom])
        format.html { redirect_to([@device, @base_rom], :notice => 'Base rom was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /base_roms/1
  # DELETE /base_roms/1.xml
  def destroy
    @device = Device.find(params[:device_id])
    @base_rom.destroy

    respond_to do |format|
      format.html { redirect_to(@device) }
    end
  end

  def purge_configs
    if @base_rom.configurations.each &:destroy
      redirect_to([@base_rom.device, @base_rom], :notice => 'Purged.')
    else
      redirect_to([@base_rom.device, @base_rom], :notice => 'An error prevented the purge.')
    end
  end

  def purge_test_configs
    if @base_rom.configurations.select{|c| c.name.start_with? '_'}.each &:destroy
      redirect_to([@base_rom.device, @base_rom], :notice => 'Purged (test).')
    else
      redirect_to([@base_rom.device, @base_rom], :notice => 'An error prevented the purge.')
    end
  end
  
protected
  
  def load_ressource
    @base_rom = BaseRom.find(params[:base_rom_id] ? params[:base_rom_id] : params[:id])
  end
end

app/helpers/base_roms_helper.rb
module BaseRomsHelper
  def uploader_name_for base_rom
    base_rom.uploader.present? ? base_rom.uploader.name : "Unknown"
  end
end

app/views/base_roms/_form.html.erb
<%= form_for([@device, @base_rom], :html => {:multipart => true}) do |f| %>
  <% if @base_rom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@base_rom.errors.count, "error") %> prohibited this base_rom from being saved:</h2>

      <ul>
      <% @base_rom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url, 'Website' %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label 'Original file' %><br />
    <b><%= (@base_rom.file_path.nil? or @base_rom.file_path.empty? ) ? 'No file yet' : @base_rom.file_path %></b><br />
    <%= file_field 'upload', 'datafile' %>
  </div>

  <div class="field">
    <%= f.check_box :dev %> <%= f.label :dev, 'In development (only visible by you)' %>
  </div>
  <div class="field">
    <%= f.check_box :old %> <%= f.label :old, 'Deprecated' %>
  </div>

  <div class="field">
    <%= f.label :info, 'Info for downloaders' %><br />
    <%= f.text_area :info %>
  </div>

  <div class="actions">
    <%= f.hidden_field :device_id %>
    <%= f.submit %>
  </div>
<% end %>

app/views/base_roms/edit.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <%= link_to @device.name, @device %> <%= image_tag 'nav_sep.png' %>
  <%= link_to @base_rom.name, [@base_rom.device, @base_rom] %> <%= image_tag 'nav_sep.png' %>
  Edit
<% end %>

<%= render 'form' %>

app/views/base_roms/new.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <%= link_to @device.name, @device %> <%= image_tag 'nav_sep.png' %>
  New Base ROM
<% end %>

<%= render 'form' %>

app/views/base_roms/show.html.erb
<% content_for :navbar do %>
  <%= link_to image_tag('home.png'), '/' %></a> <%= image_tag 'nav_sep.png' %>
  <%= link_to @base_rom.device.name, @base_rom.device %> <%= image_tag 'nav_sep.png' %>
  <%= link_to @base_rom.name, device_base_rom_configurations_path(@base_rom.device, @base_rom) %> <%= image_tag 'nav_sep.png' %>
  Details
<% end %>

<h2>Packages</h2>

<ul>
<% @base_rom.base_rom_packages.select {|p| !p.dev}.each do |base_rom_package|
     package = base_rom_package.package %>
  <li><%= package.fullname %> <%= base_rom_package.mandatory ? '(mandatory)' : '' %> | <%= link_to 'Remove', [@base_rom.device, @base_rom, base_rom_package], :method => 'DELETE', :confirm => 'Sure?' %></li>
<% end %>
</ul>

<h2>APKs</h2>

<ul>
<% @base_rom.apks.sort_by {|a| a.name}.sort_by {|a| a.expert ? 1 : 0}.each do |apk| %>
  <li>
    <strong><%= link_to apk.name, apk %></strong><%= apk.expert ? ' (expert)' : '' %><br/>
    <%= apk.description %>
  </li>
<% end %>
</ul>

<% content_for :admin do %>
  <%= link_to 'Edit info', edit_device_base_rom_path(@base_rom.device, @base_rom) %> |
  <%= link_to 'Add package', new_device_base_rom_base_rom_package_path(@base_rom.device, @base_rom) %> |
  <%= link_to 'Purge configs', device_base_rom_purge_configs_path(@base_rom.device, @base_rom), :confirm => 'Sure? You might piss someone off...' %> |
  <%= link_to 'Purge test configs', device_base_rom_purge_test_configs_path(@base_rom.device, @base_rom), :confirm => 'Sure?' %> |
  <%= link_to 'Delete', [@base_rom.device, @base_rom], :method => 'DELETE', :confirm => 'OMG are you absolutely sure? I mean, you could mark it deprecated, but deleting? Really? REALLY really?' %>
<% end %>